#!/usr/bin/env python3
"""
Story 1.8 (SI): full 8-state TD-DFT absorption table, both functionals,
straight from the real CSVs -- no manual transcription. Emits a longtable
LaTeX fragment at tables/tab_S1_absorption_states.tex.
"""
import csv
from pathlib import Path

BASE = Path(__file__).resolve().parent
# All seven candidates are emitted; every row in the CSVs is included.
MOLECULES = ["1712", "9168", "17574", "18506", "4550", "17851", "20778"]


def load(functional):
    path = BASE / "solvatochromic_tddft" / f"solvatochromic_results_{functional}.csv"
    rows = []
    with open(path) as fh:
        for row in csv.DictReader(fh):
            rows.append(row)
    return rows


def main():
    lines = [
        r"% Auto-generated by make_si_table.py -- do not edit by hand.",
        r"\begin{longtable}{l l c r r r r}",
        r"\caption{Full TD-DFT absorption states (S1-S8) for the seven candidates, in CPCM"
        r" toluene and water, at B3LYP/6-31G* and CAM-B3LYP/6-31G*.}",
        r"\label{SI-tab:absorption_states} \\",
        r"\toprule",
        r"Functional & Molecule & Solvent & State & Energy (eV) & $\lambda$ (nm) & $f_{\mathrm{osc}}$ \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Functional & Molecule & Solvent & State & Energy (eV) & $\lambda$ (nm) & $f_{\mathrm{osc}}$ \\",
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endfoot",
    ]
    order = {m: i for i, m in enumerate(MOLECULES)}
    for functional in ["B3LYP", "CAM-B3LYP"]:
        rows = sorted(
            load(functional),
            key=lambda r: (order.get(r["mol_id"], 99), r["solvent"], int(r["state"])),
        )
        for row in rows:
            lines.append(
                f"{functional} & {row['mol_id']} & {row['solvent']} & {row['state']} & "
                f"{float(row['energy_eV']):.3f} & {float(row['wavelength_nm']):.1f} & "
                f"{float(row['oscillator_strength']):.5f} \\\\"
            )
    lines.append(r"\end{longtable}")

    out = BASE / "tables" / "tab_S1_absorption_states.tex"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({sum(1 for functional in ['B3LYP','CAM-B3LYP'] for _ in load(functional))} data rows)")


if __name__ == "__main__":
    main()
