#!/usr/bin/env python3
"""
regen_tables.py — regenerate Paper-1 LaTeX tables from the rebuilt screen.

Sources: outputs/recompute/{screen_full.csv,summary.json,robustness.json} for the
candidate tables; the dataset CSV for the composition correlations (which the
Scharber recomputation cannot change, but which need CI and p per referees 2 and 4).

Emits, into tables/:
  tab_candidates.tex        the promoted molecules, all four conventions, with
                            the reason each is or is not a defensible candidate
  tab_conventions.tex       the four (absorber x FF) variants side by side:
                            pool, cascade, first place -- the convention-dependence
                            result (ledger L-2026-09-01-17)
  tab_correlations.tex      heteroatom-composition correlations + 95 % CI + p
  tab_model_settings.tex    every Scharber parameter, so the model is quotable

The submitted tab_top_candidates.tex is left on disk untouched; it is superseded
by tab_candidates.tex and its \\input is switched in the section file.

Run from the Paper-1 folder:  python regen_tables.py
"""
import json
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
REC = HERE / "outputs" / "recompute"
TABDIR = HERE / "tables"
TABDIR.mkdir(exist_ok=True)

# The corrected reorganization-energy table lives in the sibling NTO study in the
# working tree, and beside this script under data/ in the published deposit.
REORG = next((p for p in (HERE / "data" / "reorganization_energies_corrected.csv",
                          HERE.parent / "NTO_and_related_study" / "analysis" /
                          "reorganization_energies_corrected.csv") if p.exists()),
             HERE / "data" / "reorganization_energies_corrected.csv")

df = pd.read_csv(REC / "screen_full.csv")
summary = json.loads((REC / "summary.json").read_text())
robust = json.loads((REC / "robustness.json").read_text())

VARIANTS = [("strict_FF065", "strict, $FF = 0.65$"),
            ("strict_FFgreen", "strict, Green $n = 1$"),
            ("compl_FF065", "compl., $FF = 0.65$"),
            ("compl_FFgreen", "compl., Green $n = 1$")]
LEAD = 9168
QUINONE = {19598, 21736, 23450}
DYES = {22936}


def row(mid):
    return df.loc[df.mol_id == mid].iloc[0]


def fmt(x, nd=2, plus=False):
    if pd.isna(x):
        return "---"
    return f"{x:+.{nd}f}" if plus else f"{x:.{nd}f}"


# =============================================================================
# tab_candidates.tex
# =============================================================================
def tab_candidates():
    ids = sorted(set(robust["union_all_variants"]) | {LEAD})
    verdict = {}
    for mid in ids:
        if mid in QUINONE:
            verdict[mid] = "\\emph{o}-quinone tautomer (R7)"
        elif mid in DYES:
            verdict[mid] = "anthraquinone dye"
        elif mid == LEAD:
            verdict[mid] = "\\textbf{defensible}"
        else:
            verdict[mid] = "---"

    lines = [
        "% Regenerated by regen_tables.py from outputs/recompute/screen_full.csv.",
        "% Ledger: L-2026-09-01-16, -17, -19, -20, -21.",
        "\\begin{table*}[t]",
        "\\centering",
        "\\caption{Every molecule that is chemically valid, passes the stability screen and "
        "reaches $\\pcesascore > 0$ under at least one of the four modelling conventions of "
        "\\cref{tab:conventions}. Frontier energies are B3LYP/6-31G*//PM6; $\\pcesascore$ is "
        "quoted for the fixed fill factor ($FF = 0.65$) and, in parentheses, for the "
        "ideality-limited expression. Only molecule 9168 is positive under all four "
        "conventions. The final column records why the remaining entries are not defensible "
        "candidates despite clearing every numerical filter --- the point of "
        "\\cref{sec:results_r7}.}",
        "\\label{tab:candidates}",
        "\\begin{tabular}{lcccccccl}",
        "\\toprule",
        "ID & Formula & \\makecell{HOMO\\\\(\\unit{\\electronvolt})} & "
        "\\makecell{LUMO\\\\(\\unit{\\electronvolt})} & \\makecell{gap\\\\(\\unit{\\electronvolt})} & "
        "SAScore & \\makecell{PCE\\\\(\\unit{\\percent})} & $\\pcesascore$ & verdict \\\\",
        "\\midrule",
    ]
    # order: lead first, then by complementary score
    ordered = [LEAD] + sorted([i for i in ids if i != LEAD],
                              key=lambda m: -(row(m).PCE_SAScore_compl_FF065
                                              if not pd.isna(row(m).PCE_SAScore_compl_FF065)
                                              else -99))
    for mid in ordered:
        r = row(mid)
        pce = r.PCE_compl_FF065 if not pd.isna(r.PCE_compl_FF065) else r.PCE_strict_FF065
        ps065 = (r.PCE_SAScore_compl_FF065 if not pd.isna(r.PCE_SAScore_compl_FF065)
                 else r.PCE_SAScore_strict_FF065)
        psgrn = (r.PCE_SAScore_compl_FFgreen if not pd.isna(r.PCE_SAScore_compl_FFgreen)
                 else r.PCE_SAScore_strict_FFgreen)
        formula = "\\ch{" + str(r.formula) + "}"
        bold = mid == LEAD
        cells = [
            f"\\textbf{{{mid}}}" if bold else str(mid),
            formula,
            f"${fmt(r.HOMO_eV, 3, plus=True)}$",
            f"${fmt(r.LUMO_eV, 3, plus=True)}$",
            fmt(r.gap_eV, 3),
            fmt(r.SAScore, 2),
            fmt(pce, 2),
            f"${fmt(ps065, 2, plus=True)}$ (${fmt(psgrn, 2, plus=True)}$)",
            verdict[mid],
        ]
        lines.append(" & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""]
    (TABDIR / "tab_candidates.tex").write_text("\n".join(lines))
    print(f"  tab_candidates.tex      {len(ordered)} rows: {ordered}")


# =============================================================================
# tab_conventions.tex
# =============================================================================
def tab_conventions():
    lines = [
        "% Regenerated by regen_tables.py. Ledger L-2026-09-01-17.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{The screen under all four combinations of absorber convention and "
        "fill-factor expression. \\emph{Strict} requires the molecule's own gap to be the "
        "narrower of the pair; \\emph{complementary} admits any molecule absorbing in "
        "\\qtyrange{1.1}{2.2}{\\electronvolt}. The cascade counts molecules passing the "
        "physical gates, then the validity filter, then the stability screen, then "
        "$\\pcesascore > 0$. First place changes with the convention; the intersection of "
        "all four sets does not.}",
        "\\label{tab:conventions}",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "convention & cascade & \\makecell{max PCE\\\\(\\unit{\\percent})} & first place \\\\",
        "\\midrule",
    ]
    for key, label in VARIANTS:
        kind = key.split("_")[0]
        pool = df[f"passes_{kind}"].astype(bool)
        valid = pool & df.chemically_valid.astype(bool)
        stable = valid & df.stable.astype(bool)
        pos = stable & (df[f"PCE_SAScore_{key}"] > 0)
        v = summary["variants"][key]
        first = v["first"]
        cascade = f"{int(pool.sum())} $\\to$ {int(valid.sum())} $\\to$ " \
                  f"{int(stable.sum())} $\\to$ {int(pos.sum())}"
        mark = f"\\textbf{{{first}}}" if first == LEAD else str(first)
        lines.append(f"{label} & {cascade} & {v['max_pce_all']:.2f} & {mark} \\\\")
    inter = ", ".join(str(i) for i in robust["intersection_all_variants"])
    lines += [
        "\\midrule",
        f"\\multicolumn{{4}}{{l}}{{intersection of all four sets: \\textbf{{{inter}}}}} \\\\",
        "\\bottomrule", "\\end{tabular}", "\\end{table}", "",
    ]
    (TABDIR / "tab_conventions.tex").write_text("\n".join(lines))
    print(f"  tab_conventions.tex     4 variants, intersection {{{inter}}}")


# =============================================================================
# tab_model_settings.tex
# =============================================================================
def tab_model_settings():
    c = summary["constants"]
    refs = summary["references"]
    rows = [
        ("external quantum efficiency, EQE", f"{c['EQE']:.2f}", "assumed constant"),
        ("incident power, $P_{\\mathrm{in}}$",
         f"\\qty{{{c['P_in_W_m2']:.1f}}}{{\\watt\\per\\meter\\squared}}", "AM1.5G, one sun"),
        ("CT-state loss", f"\\qty{{{c['V_loss_V']:.2f}}}{{\\volt}}",
         "empirical, Scharber \\emph{et al.}"),
        ("minimum driving force",
         f"\\qty{{{c['driving_force_min_eV']:.2f}}}{{\\electronvolt}}",
         "LUMO--LUMO offset"),
        ("fill factor (fixed)", f"{c['FF_fixed']:.2f}", "primary convention"),
        ("fill factor (ideality)", f"$n = {c['FF_green_ideality']:.0f}$",
         "Green's expression, sensitivity"),
        ("absorption window",
         f"\\qtyrange{{{c['Eg_window_eV'][0]}}}{{{c['Eg_window_eV'][1]}}}{{\\electronvolt}}",
         "complementary convention only"),
        ("\\PCBM{} HOMO / LUMO",
         f"$-{abs(refs['PCBM'][0]):.1f}$ / $-{abs(refs['PCBM'][1]):.1f}$~\\unit{{\\electronvolt}}",
         "acceptor reference"),
        ("\\PCDTBT{} HOMO / LUMO",
         f"$-{abs(refs['PCDTBT'][0]):.1f}$ / $-{abs(refs['PCDTBT'][1]):.1f}$~\\unit{{\\electronvolt}}",
         "donor reference"),
        ("integrated irradiance",
         f"\\qty{{{summary['spectrum_integrated_W_m2']:.2f}}}{{\\watt\\per\\meter\\squared}}",
         "ASTM G173-03, validation"),
        ("$J_{\\mathrm{SC}}$ at \\qty{1.4}{\\electronvolt}",
         f"\\qty{{{summary['jsc_at_1p4eV_Am2']:.1f}}}{{\\ampere\\per\\meter\\squared}}",
         "validation against the literature"),
    ]
    lines = [
        "% Regenerated by regen_tables.py from outputs/recompute/summary.json.",
        "% Every quantity used by scharber_recompute.py, so a reader can reproduce any PCE.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Complete parameter set of the photovoltaic model. The two fill-factor "
        "conventions are reported throughout rather than one being chosen; the last two rows "
        "are validation checks, not inputs.}",
        "\\label{tab:model_settings}",
        "\\begin{tabular}{lll}",
        "\\toprule",
        "quantity & value & note \\\\",
        "\\midrule",
    ]
    for a, b, c_ in rows:
        lines.append(f"{a} & {b} & {c_} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    (TABDIR / "tab_model_settings.tex").write_text("\n".join(lines))
    print(f"  tab_model_settings.tex  {len(rows)} parameters, model fully quotable")


# =============================================================================
# tab_correlations.tex — unchanged data, but with CI and p (R2-6, R4-8)
# =============================================================================
def tab_correlations():
    from rdkit import Chem, RDLogger
    from scipy import stats
    RDLogger.DisableLog("rdApp.*")

    def frac(smi, el):
        m = Chem.MolFromSmiles(smi) if isinstance(smi, str) else None
        if m is None:
            return np.nan
        syms = [a.GetSymbol() for a in m.GetAtoms()]
        return 100 * syms.count(el) / len(syms) if syms else np.nan

    d = df.dropna(subset=["SMILES", "HOMO_eV", "LUMO_eV", "gap_eV"]).copy()
    for el in ("N", "O", "S"):
        d[f"f{el}"] = [frac(s, el) for s in d.SMILES]
    d = d.dropna(subset=["fN", "fO", "fS"])
    n = len(d)

    lines = [
        "% Regenerated by regen_tables.py. Ledger L-2026-09-01-09(c).",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Pearson correlation between heavy-atom heteroatom fraction and computed "
        f"frontier-orbital energies over the working set ($n = \\num{{{n}}}$), with "
        "\\qty{95}{\\percent} Fisher-$z$ confidence intervals. No coefficient exceeds "
        "$|r| = 0.35$, and the sulfur--gap coefficient is not significant, so atomic "
        "composition alone does not encode a usable design rule.}",
        "\\label{tab:correlations}",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        " & HOMO & LUMO & gap \\\\",
        "\\midrule",
    ]
    names = {"fN": "nitrogen fraction", "fO": "oxygen fraction", "fS": "sulfur fraction"}
    report = []
    for key, label in names.items():
        cells = []
        for target in ("HOMO_eV", "LUMO_eV", "gap_eV"):
            r, p = stats.pearsonr(d[key], d[target])
            z = np.arctanh(r)
            se = 1 / np.sqrt(n - 3)
            lo, hi = np.tanh(z - 1.96 * se), np.tanh(z + 1.96 * se)
            star = "" if p < 0.05 else "$^{\\dagger}$"
            cells.append(f"${r:+.3f}${star}\\newline\\scriptsize[{lo:+.3f}, {hi:+.3f}]")
            report.append(f"{key}-{target.split('_')[0]} {r:+.3f} p={p:.3g}")
        lines.append(f"{label} & " + " & ".join(f"\\makecell{{{c}}}" for c in cells) + " \\\\")
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\\\[2pt]\\footnotesize $^{\\dagger}$not significant at "
        "\\qty{5}{\\percent}; all other coefficients have $p < 10^{-7}$.",
        "\\end{table}", "",
    ]
    (TABDIR / "tab_correlations.tex").write_text("\n".join(lines))
    print(f"  tab_correlations.tex    n={n}; " + "; ".join(report[:3]) + " ...")


def tab_functional_sensitivity():
    """SI functional-sensitivity table, reporting the RIGHT quantity (T0-4).

    The submitted SI Table S4 printed 0.229 / 0.309 / 0.080 eV as
    "frontier-orbital energy" MAEs. Those are lambda_hole MAEs, taken from
    functional_sensitivity.csv, which pivots on values='lambda_hole_eV'
    (ledger L-2026-09-01-07). The true frontier MAEs are 4-8x larger. This
    table reports both, so the claim the SI makes is the claim the data supports.
    """
    from scipy import stats
    from itertools import combinations

    r = pd.read_csv(REORG)
    F = ["b3lyp", "camb3lyp", "wb97x-d3"]
    LBL = {"b3lyp": "B3LYP", "camb3lyp": "CAM-B3LYP", "wb97x-d3": "$\\omega$B97X-D3"}
    piv = {f: r[r.functional == f].set_index("mol_id") for f in F}
    ids = sorted(set(r.mol_id))

    def stat(f1, f2, cols):
        vals = []
        for q in cols:
            a = piv[f1][q].reindex(ids).astype(float)
            b = piv[f2][q].reindex(ids).astype(float)
            m = a.notna() & b.notna()
            vals += list((a[m] - b[m]).abs())
        v = np.array(vals)
        return v.mean(), np.sqrt((v ** 2).mean()), v.max()

    lines = [
        "% Regenerated by regen_tables.py. Ledger L-2026-09-01-07 (T0-4).",
        "% Replaces the submitted SI Table S4, which labelled lambda_hole MAEs as",
        "% frontier-orbital MAEs. Both quantities are now reported explicitly.",
        "\\begin{table}[h]",
        "\\centering",
        "\\caption{Functional sensitivity on the subset with optimized charged-state "
        f"geometries ($n = {len(ids)}$: "
        + ", ".join(str(i) for i in ids) +
        "). Mean absolute error, root-mean-square error and the largest single "
        "deviation are reported separately for the hole reorganization energy and for "
        "the frontier-orbital energies, because the two differ by nearly an order of "
        "magnitude. Spearman $\\rho$ is quoted for $\\lhole$. The subset contains "
        "neither molecule 1712 nor molecule 9168, so this is a consistency check on six "
        "molecules and not a validation of the screen.}",
        "\\label{tab:functional_sensitivity}",
        "\\begin{tabular}{llccccccc}",
        "\\toprule",
        "\\multirow{2}{*}{Functional 1} & \\multirow{2}{*}{Functional 2} & "
        "\\multicolumn{4}{c}{$\\lhole$ (\\unit{\\electronvolt})} & "
        "\\multicolumn{3}{c}{HOMO and LUMO (\\unit{\\electronvolt})} \\\\",
        "\\cmidrule(lr){3-6}\\cmidrule(lr){7-9}",
        " & & MAE & RMSE & max & $\\rho$ & MAE & RMSE & max \\\\",
        "\\midrule",
    ]
    report = []
    for f1, f2 in combinations(F, 2):
        lm, lr, lx = stat(f1, f2, ["lambda_hole_eV"])
        om, orms, ox = stat(f1, f2, ["E_HOMO", "E_LUMO"])
        a = piv[f1]["lambda_hole_eV"].reindex(ids).astype(float)
        b = piv[f2]["lambda_hole_eV"].reindex(ids).astype(float)
        m = a.notna() & b.notna()
        rho, _ = stats.spearmanr(a[m], b[m])
        lines.append(f"{LBL[f1]} & {LBL[f2]} & {lm:.3f} & {lr:.3f} & {lx:.3f} & "
                     f"{rho:.2f} & {om:.2f} & {orms:.2f} & {ox:.2f} \\\\")
        report.append(f"{LBL[f1]}/{LBL[f2]}: lam {lm:.3f} vs frontier {om:.2f}")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    (TABDIR / "tab_functional_sensitivity.tex").write_text("\n".join(lines))
    print("  tab_functional_sensitivity.tex  " + "; ".join(report))


def tab_reorganization():
    """SI table of the full lambda_hole set, including the 19531 counterexample (T0-5).

    The submitted Figure 7 showed 17851 and 20778 (azides, negative lambda) against
    two positive controls, and excluded 19531 -- which is NOT an azide and has
    lambda_hole an order of magnitude more negative, with a failed anion SCF
    (ledger L-2026-09-01-08). Excluding it makes the azide attribution look
    stronger than the data supports.
    """
    r = pd.read_csv(REORG)
    F = ["b3lyp", "camb3lyp", "wb97x-d3"]
    piv = {f: r[r.functional == f].set_index("mol_id") for f in F}
    ids = sorted(set(r.mol_id))
    NOTE = {17851: "azide", 20778: "azide",
            19531: "\\textbf{chloride ion pair}; formula not applicable",
            977: "\\ch{O2}, not a molecule of interest",
            14380: "wide gap (\\qty{5.23}{\\electronvolt}); sulfonamide",
            18985: "wide gap (\\qty{5.37}{\\electronvolt}); pyridyl imine"}

    lines = [
        "% Regenerated by regen_tables.py. Ledger L-2026-09-01-08, -22 (T0-5).",
        "\\begin{table}[h]",
        "\\centering",
        "\\caption{Four-point hole reorganization energy for every molecule in the "
        "charged-state subset. Molecule 19531 is a pyrrolidinium ester "
        "chloride ion pair, rejected by the validity filter as a multi-fragment "
        "species: removing an electron redistributes charge between its fragments "
        "rather than ionising a neutral molecule, so the four-point expression does "
        "not describe a reorganization and its value is not comparable with the "
        "others. Its $\\lhole$ is nevertheless an order of magnitude more negative "
        "than either azido-triazine, which shows that a negative $\\lhole$ in this "
        "subset is not specific to the azide group. Molecules 14380 and "
        "18985 are the two remaining members of the same convenience batch, and their "
        "gaps of \\qtylist{5.23;5.37}{\\electronvolt} place both far outside the "
        "photovoltaic window, so they fix the sign of $\\lhole$ for ordinary "
        "closed-shell molecules and support nothing beyond that.}",
        "\\label{tab:reorganization}",
        "\\begin{tabular}{lccccl}",
        "\\toprule",
        "ID & \\makecell{$\\lhole$ B3LYP\\\\(\\unit{\\electronvolt})} & "
        "\\makecell{CAM-B3LYP\\\\(\\unit{\\electronvolt})} & "
        "\\makecell{$\\omega$B97X-D3\\\\(\\unit{\\electronvolt})} & "
        "SCF status & note \\\\",
        "\\midrule",
    ]
    order = sorted(ids, key=lambda m: piv["b3lyp"].loc[m, "lambda_hole_eV"])
    for mid in order:
        vals, status = [], "converged"
        for f in F:
            row_ = piv[f].loc[mid]
            vals.append(row_["lambda_hole_eV"])
            if row_["status"] != "success":
                status = "\\textbf{" + str(row_["status"]).replace("_", "\\_") + "}"
        cells = " & ".join(f"${v:+.3f}$" for v in vals)
        lines.append(f"{mid} & {cells} & {status} & {NOTE.get(mid, '')} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    (TABDIR / "tab_reorganization.tex").write_text("\n".join(lines))
    neg = [m for m in order if piv["b3lyp"].loc[m, "lambda_hole_eV"] < 0]
    print(f"  tab_reorganization.tex  {len(order)} molecules, negative lambda: {neg}")


def tab_comparators():
    """Known organic semiconductors that are IN the shard, and how the screen
    treats them. This is referee point 4.2 answered internally: rather than
    comparing our B3LYP numbers against someone else's measurements, the nine
    reference hydrocarbons present in the same shard are run through the same
    gates. None is admitted. That calibrates the screen against materials whose
    device behaviour is established, at the same level of theory, reproducibly.
    Evidence: outputs/extract/referee-verification-{18,19}.txt, comparators.csv.
    """
    NAMES = [(241, "Benzene"), (931, "Naphthalene"), (995, "Phenanthrene"),
             (8418, "Anthracene"), (7080, "Tetracene"), (9171, "Chrysene"),
             (9162, "Picene"), (9115, "Coronene"), (8671, "Pentacene")]
    LUMO_PCBM, LUMO_PCDTBT = -3.700, -3.600
    GAP_LO, GAP_HI = 1.1, 2.2

    lines = [
        "% Regenerated by regen_tables.py. Ledger L-2026-09-02-23.",
        "\\begin{table*}[t]",
        "\\centering",
        "\\caption{Established organic semiconductors present in the same shard, run "
        "through the same screen. Frontier energies are the dataset's own "
        "B3LYP/6-31G*//PM6 values, so the comparison needs no external calibration. "
        "$\\Delta E_{\\mathrm{L}}$ is the LUMO--LUMO offset against \\PCBM{} in the "
        "donor pairing. None of the nine is admitted, and in every case the "
        "computed one-electron gap---not the offsets---is what excludes it: all nine "
        "lie above the "
        f"\\qtyrange{{{GAP_LO}}}{{{GAP_HI}}}{{\\electronvolt}} absorption window. "
        "Measured optical gaps for these materials are far smaller than their "
        "Kohn--Sham gaps, which is the systematic error a frontier-orbital screen "
        "carries and cannot detect.}",
        "\\label{tab:comparators}",
        "\\begin{tabular}{llrrrrrl}",
        "\\toprule",
        "Molecule & Formula & \\makecell{HOMO\\\\(\\unit{\\electronvolt})} & "
        "\\makecell{LUMO\\\\(\\unit{\\electronvolt})} & "
        "\\makecell{$E_g$\\\\(\\unit{\\electronvolt})} & "
        "\\makecell{$\\Delta E_{\\mathrm{L}}$\\\\(\\unit{\\electronvolt})} & "
        "SAScore & admitted? \\\\",
        "\\midrule",
    ]
    for mid, name in NAMES:
        r = df[df.mol_id == mid]
        if r.empty:
            continue
        r = r.iloc[0]
        dl = r.LUMO_eV - LUMO_PCBM
        adm = bool(r.passes_strict) or bool(r.passes_compl)
        why = "no: $E_g$ above window" if not adm else "yes"
        lines.append(
            f"{name} & \\ch{{{r.formula}}} & ${r.HOMO_eV:+.3f}$ & ${r.LUMO_eV:+.3f}$ & "
            f"{r.gap_eV:.3f} & ${dl:+.3f}$ & {r.SAScore:.2f} & {why} \\\\")
    g = df[df.mol_id == 9168].iloc[0]
    lines += [
        "\\midrule",
        f"\\textbf{{9168}} (this work) & \\ch{{{g.formula}}} & ${g.HOMO_eV:+.3f}$ & "
        f"${g.LUMO_eV:+.3f}$ & \\textbf{{{g.gap_eV:.3f}}} & "
        f"${g.LUMO_eV - LUMO_PCBM:+.3f}$ & {g.SAScore:.2f} & yes \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table*}", "",
    ]
    (TABDIR / "tab_comparators.tex").write_text("\n".join(lines))
    n_adm = sum(1 for mid, _ in NAMES
                if not df[df.mol_id == mid].empty
                and (bool(df[df.mol_id == mid].iloc[0].passes_strict)
                     or bool(df[df.mol_id == mid].iloc[0].passes_compl)))
    print(f"  tab_comparators.tex     {len(NAMES)} comparators, {n_adm} admitted")


if __name__ == "__main__":
    print("regenerating LaTeX tables from outputs/recompute/")
    tab_candidates()
    tab_conventions()
    tab_model_settings()
    tab_correlations()
    tab_functional_sensitivity()
    tab_reorganization()
    tab_comparators()
    print("done")
